version: 2.1
workflows:
  main:
    jobs:
      - build-docs:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - deploy-docs:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
          requires:
            - build-docs

job-references:
  env-latest: &env-latest
    docker:
      - image: julia:latest

  restore_julia_in_docs: &restore_julia_in_docs
    keys:
      - deps-{{ checksum "docs/Project.toml" }}
      - deps-

  install_julia_in_docs: &install_julia_in_docs
    name: Install Julia dependencies
    command: |
      cp docs/Project.toml docs/Project.toml.old
      julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'

  save_julia_in_docs: &save_julia_in_docs
    key: deps-{{ checksum "docs/Project.toml.old" }}
    paths:
      - ~/.julia/compiled
      - ~/.julia/packages
      - ~/.julia/registries

jobs:
  build-docs:
    <<: *env-latest
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout

      - restore_cache: *restore_julia_in_docs
      - run: *install_julia_in_docs
      - save_cache: *save_julia_in_docs

      - run:
          name: Build documentation
          command: julia --project=docs/ docs/make.jl
      - persist_to_workspace:
          root: docs/build
          paths:
            - "*"
      - run:
          name: Compress Artifacts
          command: tar -cvf docs.tar docs/build
      - store_artifacts:
          path: docs.tar
  deploy-docs:
    <<: *env-latest
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout

      - restore_cache: *restore_julia_in_docs
      - run: *install_julia_in_docs
      - save_cache: *save_julia_in_docs

      - attach_workspace:
          at: docs/build
      - run:
          name: Deploy documentation to GitHub pages
          command: julia --project=docs/ docs/deploy.jl
