name: "CI"
on:
  push:
    branches: "*"
  pull_request:
env:
  cache-version: 1
jobs:
  unit:
    name: "Unit tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1.0'
          - '1'
        arch:
          - x86
          - x64
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Setup Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: "Run unit tests"
        uses: julia-actions/julia-runtest@v1
